name: Push to Another Repository

on:
  push:
    branches: [ master ]

jobs:
  push_to_target:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
      fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: push
      run: |
        git remote add other-account https://github.com/Abuyin2004/apple_tobacco.git 
        git push other-account master