name: Push to Another Repository

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets._GITHUB_TOKEN_Abuyin2004 }}
        with:
          source-directory: '.'
          destination-github-username: 'Abuyin2004'
          destination-repository-name: 'apple_tobacco'
          user-email: carles3@pina.cat
          target-branch: master