name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: source-code
        path: .

    - name: Push artifact to another repository
      run: |
        git clone https://${{ secrets.GITHUB_TOKEN_Abuyin2004 }}@github.com/Abuyin2004/apple_tobacco.git target-repo
        cd target-repo
        git checkout master
        git fetch
        git reset --hard origin/master
        rm -rf *
        mv ../source-code/* .
        git add .
        git commit -m "Update from source repository"
        git push origin master --force