name: CI

on:
  push:
    branches: [ master ]

jobs:
  push_to_target:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # This is important to fetch all branches and tags

    - name: Push to target repository
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN_Abuyin2004 }}
      run: |
        git remote add target https://${{ secrets.GITHUB_TOKEN_Abuyin2004 }}@github.com/Abuyin2004/apple_tobacco.git
        git push target master --force
